#!/bin/bash
setup_certs() {
    sleep 30
    certbot -n --nginx --agree-tos -m lukas@some.engineering -d cloudkeeper.sh
    while :
    do
        sleep 604800
        certbot renew --quiet
    done
}
setup_certs &
/docker-entrypoint.sh "$@"
